### ISSUE TITLE
Could you please share the training data?

### ISSUE THREAD

**Issue by hbc2020** [diptamath/Nonhomogeneous_Image_Dehazing#1]
Hi,
I am really interested in this paper, could you please share the training data on Google Driver? Thanks!

**Comment by saikatdutta** [comment]
Sorry, we don't have permission to share the dataset. Please contact the authors of [this paper](https://arxiv.org/abs/2005.03560#:~:text=NH%2DHAZE%3A%20An%20Image%20Dehazing%20Benchmark%20with%20Non%2DHomogeneous,Hazy%20and%20Haze%2DFree%20Images&text=This%20is%20the%20first%20non,real%20conditions%20of%20hazy%20scenes.) for the dataset.

**Comment by hbc2020** [comment]
Thank you all the same, I have tested your trained model on Dense Haze directly, however the quality of the output images is not good. Did you test this model on any other Dehazing datasets other than NH-Haze? Are there any parameter settings that I need to pay more attention?

**Comment by saikatdutta** [comment]
The provided checkpoint is only for Non-homogeneous dehazing. You have to train separately on Dense-haze dataset for Dense haze removal.

**Comment by hbc2020** [comment]
I see, thank you very much for your help.
