### ISSUE TITLE
Problem with CUDA

### ISSUE THREAD

**Issue by AMBBe** [diptamath/Nonhomogeneous_Image_Dehazing#3]
I have a laptop with 2GB ram nvidia graphic card. but after run DMPHN-train.py, I have this error:

RuntimeError: CUDA out of memory. Tried to allocate 470.00 MiB (GPU 0; 2.00 GiB total capacity; 942.47 MiB already allocated; 247.93 MiB free; 948.00 MiB reserved in total by PyTorch)

I'm using:
python 3.8.8
pytorch 1.8
cudatoolkit 10.2.89
scikit-image 0.16.2

I'm adding "torch.cuda.empty_cache()" but it's not work

**Comment by saikatdutta** [comment]
2 GB GPU memory may not be sufficient to train this network. Use colab instead.

**Comment by AMBBe** [comment]
Thanks. I test it with PC

**Comment by AMBBe** [comment]
Hi. Can I run this code with 6 GB Nvidia graphic card?
