### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Aomrlyliliya** [diptamath/Nonhomogeneous_Image_Dehazing#7]
Excuse me!Can you provide the NH-HAZE dataset?I  only can find the val dataset of 5 pictures in your project.Where is the train data?

**Comment by saikatdutta** [comment]
You have to register here to get the data: https://competitions.codalab.org/competitions/22236#participate
Or, please contact the competition organizers.

**Comment by Aomrlyliliya** [comment]
OK.Thank you so much!
