### ISSUE TITLE
NH-HAZE dataaset

### ISSUE THREAD

**Issue by Aomrlyliliya** [diptamath/Nonhomogeneous_Image_Dehazing#8]
I'm so regret to say that I can't find the NH-HAZE dataset from the website you offered me yesterday.Can you provide me?Thank you so much!

**Comment by saikatdutta** [comment]
Please contact the competition organisers regarding the dataset. Thanks.

**Comment by Aomrlyliliya** [comment]
Hi!Excuse me. I would like to ask, there are 45 pairs of training data in the NH-HAZE dataset, each image is divided into 100 non-overlapping blocks, will the divided images be stored in the project file? Running the code shows:No such file or directory: /new_dataset/train\\HAZY\\800_600_18.png'
Chunked images are not stored in folders.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "diptamath/Nonhomogeneous_Image_Dehazing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [diptamath/Nonhomogeneous_Image_Dehazing] NH-HAZE dataaset (Issue #8)





 
Please contact the competition organisers regarding the dataset. Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
